# Generated by Django 4.2.7 on 2023-12-11 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorie",
            options={},
        ),
        migrations.AlterModelOptions(
            name="cycle",
            options={},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={},
        ),
    ]
